# Generated by Django 2.1.2 on 2018-10-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=1000)),
                ('publisher', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=250)),
            ],
        ),
    ]
