# Generated by Django 2.1.2 on 2018-10-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
