# Generated by Django 2.1.2 on 2018-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1, max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(upload_to=''),
        ),
    ]
